version: '3.8'
services:
  deepseek-r1-rag:
    build: .
    container_name: deepseek-r1-rag
    ports:
      - "8501:8501"
      - "11434:11434"  # Expose Ollama port
    volumes:
      - ./data:/app/data
    command: >
      bash -c "
      ollama serve &
      /wait-for-it.sh localhost:11434 --timeout=60 --strict -- \
        ollama pull deepseek-r1 && \
        streamlit run app.py --server.address=0.0.0.0
      "